import { createAction } from '@reduxjs/toolkit';
import type { AuthorizationStatusType } from '../types/authorization-status';
import type { OffersList } from '../types/offer';
import type { ReviewsList } from '../types/review';
export const toggleFavoriteLocal = createAction<string>('offer/toggleFavoriteLocal');
export const requireAuthorization = createAction<AuthorizationStatusType>('user/requireAuthorization');
export const offersCityList = createAction<OffersList>('data/offersCityList');
export const setOffersDataLoadingStatus = createAction<boolean>('data/setOffersDataLoadingStatus');
export const setError = createAction<string | null>('error/setError');
export const setSortType = createAction<string>('data/setSortType');
export const changeCity = createAction<string>('data/changeCity');
export const toggleFavorite = createAction<string>('offer/toggleFavorite');
export const setFavoriteStatus = createAction<{ offerId: string; status: boolean }>('offer/setFavoriteStatus');
export const setReviews = createAction<ReviewsList>('reviews/setReviews');
export const setUserData = createAction<{
  id: string;
  email: string;
  username: string;
  avatar: string;
  isPro: boolean;
} | null>('user/setUserData');